rpc:
  mainnet:
    uri: ${MAINNET_RPC_URI:-https://rpc.tzkt.io/mainnet}
    timeout: 20
#  florencenet:
#    uri: ${TESTNET_RPC_URI:-https://rpc.tzkt.io/florencenobanet}
#    timeout: 20
#  granadanet:
#    uri: ${NEXTNET_RPC_URI:-https://rpc.tzkt.io/granadanet}
#    timeout: 20
#  hangzhounet:
#    uri: https://rpc.tzkt.io/hangzhounet
#    timeout: 20
  hangzhou2net:
    uri: https://rpc.tzkt.io/hangzhou2net
    timeout: 20

tzkt:
  mainnet:
    uri: https://api.tzkt.io/v1/
    base_uri: https://tzkt.io/
    timeout: 20

services:
  mainnet:
    mempool: https://mempool.dipdup.net/v1/graphql
#  florencenet:
#    mempool: https://mempool.staging.dipdup.net/v1/graphql
#  hangzhounet:
#    mempool: https://mempool.staging.dipdup.net/v1/graphql
  hangzhou2net:
    mempool: https://mempool.staging.dipdup.net/v1/graphql

storage:
  pg: "host=${DB_HOSTNAME:-db} port=5432 user=${POSTGRES_USER} dbname=indexer password=${POSTGRES_PASSWORD} sslmode=disable"
  elastic:
    - ${ELASTIC_URI:-http://elastic:9200}
  es_username: ${ELASTIC_USERNAME:-admin}
  es_password: ${ELASTIC_PASSWORD:-admin}
  timeout: 10

sentry:
  environment: production
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: false

share_path: /etc/bcd

base_url: https://better-call.dev

ipfs:
  - ${SANDBOX_IPFS_GATEWAY:-https://ipfs.baking-bad.org}
  - https://cloudflare-ipfs.com
  - https://ipfs.io

domains:
   edo2net: KT1KP2Yy6MNkYKkHqroGBZ7KFN5NdNfnUHHv
#  mainnet: KT1GBZmSxmnKJXGMdMLbugPfLyUPmuLSMwKS

api:
  project_name: api
  bind: ":14000"
  swagger_host: "api.better-call.dev"
  cors_enabled: false
  sentry_enabled: true
  seed_enabled: false
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: true
    mempool_enabled: true
    sandbox_mode: false
  networks:
    - mainnet
 #   - florencenet
 #   - granadanet
 #   - hangzhounet
    - hangzhou2net
  pinata:
    key: ${PINATA_KEY}
    secret_key: ${PINATA_SECRET_KEY}
    timeout_seconds: 10
  connections:
    max: 50
    idle: 10


indexer:
  project_name: indexer
  sentry_enabled: true
  skip_delegator_blocks: false
  networks:
    mainnet:
      boost: tzkt
  #  florencenet:
  #  granadanet:
  #  hangzhounet:
  #  hangzhou2net:
  connections:
    max: 5
    idle: 5

metrics:
  project_name: metrics
  sentry_enabled: true
  cache_aliases_seconds: 30
  connections:
    max: 20
    idle: 20

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
   # - florencenet
   # - granadanet
   # - hangzhounet
    - hangzhou2net
  connections:
    max: 5
    idle: 5

graphql:
  db: "host=${DB_HOSTNAME} port=5432 user=graphql dbname=indexer password=${POSTGRES_GRAPHQL} sslmode=disable"
